#!/usr/bin/env python
"""
SConstruct for the kbterrain GDExtension (Kittenbaticorn terrain).

Based on the godot-cpp SConstruct pattern. Supports Windows and
Web (Emscripten) builds.

Flags:
    platform=windows | web
    target=template_debug | template_release
    tests=yes             Include GoogleTest sources + test_*.cpp
                          files. Gates test code via
                          KBTERRAIN_TESTS_ENABLED.

Prerequisites:
    - Submodules initialised:
          git submodule update --init --recursive
    - Python + SCons on PATH.
    - For Windows: MSVC.
    - For Web: Emscripten SDK (emsdk) activated in the shell.
"""

import glob
import os
import sys


EXTENSION_NAME = "kbterrain"
GODOT_CPP_PATH = os.environ.get("GODOT_CPP_PATH", "godot-cpp")
GOOGLETEST_PATH = os.environ.get("GOOGLETEST_PATH", "googletest")


# Verify submodules are present.
if not os.path.isdir(GODOT_CPP_PATH) or not os.listdir(GODOT_CPP_PATH):
    print(
        "ERROR: {} is not initialised. Run:\n"
        "    git submodule update --init --recursive".format(GODOT_CPP_PATH),
        file=sys.stderr,
    )
    sys.exit(1)


# Read the `tests` argument before handing off to godot-cpp, and
# remove it so godot-cpp does not emit an "Unknown SCons variables"
# warning.
includes_tests = ARGUMENTS.get("tests", "no") == "yes"
ARGUMENTS.pop("tests", None)


# godot-cpp's SConstruct sets up the compilation env, including
# platform/target/arch handling.
env = SConscript(os.path.join(GODOT_CPP_PATH, "SConstruct"))

env.Append(CPPPATH=["src/"])

# ---- Tests flag ----
if includes_tests:
    if not os.path.isdir(GOOGLETEST_PATH) or not os.listdir(GOOGLETEST_PATH):
        print(
            "ERROR: {} is not initialised. Run:\n"
            "    git submodule update --init --recursive".format(
                GOOGLETEST_PATH
            ),
            file=sys.stderr,
        )
        sys.exit(1)

    env.Append(CPPDEFINES=["KBTERRAIN_TESTS_ENABLED"])
    env.Append(
        CPPPATH=[
            os.path.join(GOOGLETEST_PATH, "googletest"),
            os.path.join(GOOGLETEST_PATH, "googletest", "include"),
            os.path.join(GOOGLETEST_PATH, "googlemock"),
            os.path.join(GOOGLETEST_PATH, "googlemock", "include"),
        ]
    )


# ---- Source files ----
sources = Glob("src/*.cpp") + Glob("src/terrain/*.cpp")

if includes_tests:
    sources += [
        os.path.join(GOOGLETEST_PATH, "googletest", "src", "gtest-all.cc"),
        os.path.join(GOOGLETEST_PATH, "googlemock", "src", "gmock-all.cc"),
    ]


# ---- Output ----
if env["platform"] == "macos":
    library_suffix = ".{}.{}.framework/{}".format(
        env["platform"], env["target"], EXTENSION_NAME
    )
else:
    library_suffix = ".{}.{}.{}{}".format(
        env["platform"],
        env["target"],
        env["arch"],
        env["SHLIBSUFFIX"],
    )

library_path = "bin/lib{}{}".format(EXTENSION_NAME, library_suffix)

library = env.SharedLibrary(library_path, source=sources)

Default(library)


# ---- Install into addons/ ----
install_path = os.path.join(
    "..", "addons", EXTENSION_NAME, "bin"
)
install_target = env.Install(install_path, library)
env.Alias("install", install_target)


Help(
    """
kbterrain build
===============

Usage:
    scons platform=<windows|web> [target=<template_debug|template_release>] [tests=yes]
    scons install  # also copies library into addons/kbterrain/bin/

Platforms:
    windows, web

Targets:
    template_debug (default), template_release

Arguments:
    tests=yes   Compile with GoogleTest and KBTERRAIN_TESTS_ENABLED.

Environment variables:
    GODOT_CPP_PATH    Path to godot-cpp (default: ./godot-cpp).
    GOOGLETEST_PATH   Path to googletest (default: ./googletest).
"""
)
